Repository hmcts/div-case-data-formatter, pull requests merged in 2020-09, with the labels that each got.

#216 Feature/security fix
  Jenkinsfile_nightly
  audit.json
  build.gradle
  security.sh
Labels: ns:divorce, prd:div, rel:div-cfs-pr-216

#214 RPET-263 Upgrade to Java 11
  Dockerfile
  build.gradle
  lombok.config
Labels: ns:divorce, prd:div, rel:div-cfs-pr-214

#219 Update README.md java reference
  README.md
Labels: ns:divorce, prd:div, rel:div-cfs-pr-219

#220 DIV-6532-Storing-and-visibility-of-multiple-Service-refusal-documents
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/CCDToDivorceFormatTest.java
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/serviceapplicationdocumentscase.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/service-application-documents.json
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/impl/CaseFormatterServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/TransformToDivorceFormatITest.java
  src/test/resources/fixtures/ccdtodivorcemapping/ccd/service-application-documents-case.json
Labels: ns:divorce, prd:div, rel:div-cfs-pr-220
