Repository hmcts/div-case-data-formatter, pull requests merged in 2020-01, with the labels that each got.

#190 Refresh project for AKS migration
  .editorconfig
  Dockerfile
  build.gradle
  charts/div-cfs/Chart.yaml
  charts/div-cfs/requirements.yaml
  charts/div-cfs/values.aat.template.yaml
  charts/div-cfs/values.preview.template.yaml
  charts/div-cfs/values.yaml
  config/checkstyle/checkstyle.xml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  ruleset.xml
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/config/HttpConnectionConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/controller/CaseFormatterController.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DaCaseData.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnCaseData.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/insights/AppInsights.java
  src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnClarificationMapper.java
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/AddDocumentsSolicitorITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/TransformToCCDFormatITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/TransformToDivorceFormatITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/insights/AppInsightsTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DocumentCollectionDocumentRequestMapperUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ccdtodivorceformat/DocumentsMappingUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/impl/SeparationDateServiceImplUTest.java
Labels: ns:div-cfs-pr-190

#192 Go live on AKS
  Jenkinsfile_CNP
Labels: ns:div-cfs-pr-192

#194 Cleanup ASE
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:divorce, rel:div-cfs-pr-194

#195 Update security.sh
  security.sh
Labels: ns:divorce, rel:div-cfs-pr-195
