Repository hmcts/div-case-data-formatter, pull requests merged in 2021-08, with the labels that each got.

#254 DFR-517: Migrate from bintray to jitpack
  build.gradle
  charts/div-cfs/Chart.yaml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-254

#253 Updated dependencies for tomcat, jacoco, serenity
  build.gradle
Labels: ns:divorce, prd:div, rel:div-cfs-pr-253

#255 DFR-464: Fortify setup
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-255
