Repository hmcts/div-case-data-formatter, pull requests merged in 2021-03, with the labels that each got.

#243 Update dependencies
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-243

#244 removed some CVE suppressions
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-244

#245 update packages
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-245

#247 Bumping up div-common-lib version
  build.gradle
Labels: ns:divorce, prd:div, rel:div-cfs-pr-247

#241 RPET-664: Brexit sol changes
  build.gradle
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/jurisdictionall.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/additional-payment.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/how-name-changed.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-6-12.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-all.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/payment.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-adultery.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-desertion.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-unreasonable-behaviour.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/same-sex.json
  src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/service-application-documents.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/additionalpayment.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/addresscase.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/hownamechanged.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdiction612.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdictionall.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentcase.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentidonly.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonadultery.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasondesertion.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonunreasonablebehaviour.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/samesex.json
  src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/jurisdiction-all.json
Labels: ns:divorce, prd:div, rel:div-cfs-pr-241
