Repository hmcts/div-case-data-formatter, pull requests merged in 2022-09, with the labels that each got.

#278 dependency-suppression fix
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-278

#279 dependency-suppression fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-279

#280 nightly-dev: Updated snake.yaml version to 1.33
  build.gradle
Labels: ns:divorce, prd:div, rel:div-cfs-pr-280
