Repository hmcts/div-case-data-formatter, pull requests merged in 2022-05, with the labels that each got.

#267 Autoscaling div-cfs
  charts/div-cfs/Chart.yaml
  charts/div-cfs/values.yaml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-267

#268 Bumping tomcat
  build.gradle
Labels: ns:divorce, prd:div, rel:div-cfs-pr-268

#269 Bumping springframework
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cfs-pr-269
